//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace CaseMaker.Localization
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp =
                        new ResourceManager("CaseMaker.Localization.Resources", typeof (Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to The dependency is needed to generate the combinations.
        /// </summary>
        public static string AbstractCombinationGenerator_ValidateModel_Dependency
        {
            get
            {
                return
                    ResourceManager.GetString("AbstractCombinationGenerator_ValidateModel_Dependency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The dependency needs at least 2 elements to generate combinations.
        /// </summary>
        public static string AbstractCombinationGenerator_ValidateModel_ElementsNeeded
        {
            get
            {
                return
                    ResourceManager.GetString("AbstractCombinationGenerator_ValidateModel_ElementsNeeded",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The maximal number of combinations must be higher than zero.
        /// </summary>
        public static string AbstractCombinationGenerator_ValidateModel_MaximalNumberOfCombHigh
        {
            get
            {
                return
                    ResourceManager.GetString("AbstractCombinationGenerator_ValidateModel_MaximalNumberOfCombHigh",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The dependency needs at least 2 selected equivalence classes from different elements.
        /// </summary>
        public static string AbstractCombinationGenerator_ValidateModel_NeededEquivalenceClasses
        {
            get
            {
                return
                    ResourceManager.GetString("AbstractCombinationGenerator_ValidateModel_NeededEquivalenceClasses",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to valor de ejemplo.
        /// </summary>
        public static string cadena
        {
            get { return ResourceManager.GetString("cadena", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Saving Item.
        /// </summary>
        public static string DefaultDao_AddNew_ErrorSaving
        {
            get { return ResourceManager.GetString("DefaultDao_AddNew_ErrorSaving", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Getting Item.
        /// </summary>
        public static string DefaultDao_GetItem_ErrorGetting
        {
            get { return ResourceManager.GetString("DefaultDao_GetItem_ErrorGetting", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximal number of negative test cases reached.
        /// </summary>
        public static string NegativeTestCasesGenerator_Generate_maxreached
        {
            get { return ResourceManager.GetString("NegativeTestCasesGenerator_Generate_maxreached", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of combinations to be generated is higher than the allowed maximal number of combinations.
        /// </summary>
        public static string PermutationCombinationGenerator_ValidateModel_Error
        {
            get { return ResourceManager.GetString("PermutationCombinationGenerator_ValidateModel_Error", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximal number of positive test cases reached.
        /// </summary>
        public static string PositiveTestCasesGenerator_Generate_maxreached
        {
            get { return ResourceManager.GetString("PositiveTestCasesGenerator_Generate_maxreached", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PresentationLayer_Button_Cancel
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_Cancel", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PresentationLayer_Button_Ok
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_Ok", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Combination.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_Create
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Combinations_Create", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Combination.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_Delete
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Combinations_Delete", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Combination.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_Edit
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Combinations_Edit", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to By All Pair.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_GenerateCombinations_ByAllPair
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_Button_ToolTip_Combinations_GenerateCombinations_ByAllPair", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By Permutation.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_GenerateCombinations_ByPermutation
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_Button_ToolTip_Combinations_GenerateCombinations_ByPermutation",
                        resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merge combinations.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_Merge
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Combinations_Merge", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Separate Merge.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Combinations_SeparateMerge
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_Button_ToolTip_Combinations_SeparateMerge",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Dependency.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Dependency_Create
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Dependency_Create", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Dependency.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Dependency_Delete
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Dependency_Delete", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Dependency.
        /// </summary>
        public static string PresentationLayer_Button_ToolTip_Dependency_Edit
        {
            get { return ResourceManager.GetString("PresentationLayer_Button_ToolTip_Dependency_Edit", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PresentationLayer_General_Description
        {
            get { return ResourceManager.GetString("PresentationLayer_General_Description", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to CM effect, failure.
        /// </summary>
        public static string PresentationLayer_General_Failure
        {
            get { return ResourceManager.GetString("PresentationLayer_General_Failure", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated Description.
        /// </summary>
        public static string PresentationLayer_General_GeneratedDescription
        {
            get { return ResourceManager.GetString("PresentationLayer_General_GeneratedDescription", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to CM effect, irrelevant.
        /// </summary>
        public static string PresentationLayer_General_Irrelevant
        {
            get { return ResourceManager.GetString("PresentationLayer_General_Irrelevant", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to CM effect, negative.
        /// </summary>
        public static string PresentationLayer_General_Negative
        {
            get { return ResourceManager.GetString("PresentationLayer_General_Negative", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to CM effect, positive.
        /// </summary>
        public static string PresentationLayer_General_Positive
        {
            get { return ResourceManager.GetString("PresentationLayer_General_Positive", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PresentationLayer_TestCase_Element_Description
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_Element_Description", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string PresentationLayer_TestCase_Element_Name
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_Element_Name", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to ObjectTypes.
        /// </summary>
        public static string PresentationLayer_TestCase_Element_ObjectTypes
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_Element_ObjectTypes", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PresentationLayer_TestCase_EquivalenceClass_Description
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_TestCase_EquivalenceClass_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string PresentationLayer_TestCase_EquivalenceClass_Effects
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_EquivalenceClass_Effects", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to EquivalenceClass.
        /// </summary>
        public static string PresentationLayer_TestCase_EquivalenceClass_Name
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_EquivalenceClass_Name", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string PresentationLayer_TestCase_EquivalenceClass_State
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_EquivalenceClass_State", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PresentationLayer_TestCase_EquivalenceClass_Value
        {
            get { return ResourceManager.GetString("PresentationLayer_TestCase_EquivalenceClass_Value", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Pairs.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Combination_AllPairsOrigin
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Combination_AllPairsOrigin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Combination already exists..
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Combination_ErrorMsg
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Combination_ErrorMsg",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Combination_ManualOrigin
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Combination_ManualOrigin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permutation.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Combination_PermutationOrigin
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Combination_PermutationOrigin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Info.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Dependencies_CreateInfo
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Dependencies_CreateInfo",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dependent Elements.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Dependencies_DependentElements
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Dependencies_DependentElements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Dependencies_Description
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Dependencies_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dependency.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Dependencies_Name
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Dependencies_Name",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Expected Results.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Effect_AddResult
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Effect_AddResult",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected Results.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Effect_ExpectedResults
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Effect_ExpectedResults",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Expected Results.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Effect_RemoveResults
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Effect_RemoveResults",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected Results.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_EffectTab_ExpResults
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_EffectTab_ExpResults",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_EffectTab_General
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_EffectTab_General",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_EffectTab_Requirements
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_EffectTab_Requirements",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_EquivalenceTab_Effects
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_EquivalenceTab_Effects",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_EquivalenceTab_General
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_EquivalenceTab_General",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Requirement.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_Add
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Requirements_Add",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assigned Requirements.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_Assigned
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Requirements_Assigned",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requirement already exists..
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_ErrorMsg
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Requirements_ErrorMsg",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Requirement.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_New
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Requirements_New",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Requirement.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_Remove
        {
            get
            {
                return
                    ResourceManager.GetString("PresentationLayer_WorkSpace_Project_TestObject_Requirements_Remove",
                                              resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string PresentationLayer_WorkSpace_Project_TestObject_Requirements_Requirements
        {
            get
            {
                return
                    ResourceManager.GetString(
                        "PresentationLayer_WorkSpace_Project_TestObject_Requirements_Requirements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At Least One dependency is needed to generate test cases.
        /// </summary>
        public static string TestCaseGenerator_ValidateModel_noDependenciesAdded
        {
            get { return ResourceManager.GetString("TestCaseGenerator_ValidateModel_noDependenciesAdded", resourceCulture); }
        }
    }
}